### ISSUE TITLE
Freeing Hierarchy from any dependence on streaming libraries

### ISSUE THREAD

**Issue by jwiegley** [jwiegley/hierarchy#8]
Hi @capitanbatata,

I think I'd like to take back maintenance of `hierarchy`, since I'm going to be using it a fair bit in the `hnix` project. I'm also going to generalize this library away from any dependence on a particular streaming library, instead choosing the simpler `LogicT` transformer as the foundation and implementation of `ListT`. See pull request #7 which implements this change. I have a supporting PR for `pipes-files` coming shortly. I will likely also create a new `files` like library that doesn't need `pipes`, which is really overkill for the problem we're solving.

**Comment by dnadales** [comment]
Hi John, sure. The reason why I needed hierarchy was to be able to put another package (argon) which depended on pipes-files. After trying to update pipes-files I discover that this package could not be built on windows (a requirement of my current project). So I removed the pipes-files dependency from argon.

All in all feel free to remove me as maintainer, and I'm happy to see that some work is taking place around file streaming libraries for Haskell.

**Comment by jwiegley** [comment]
@capitanbatata Ah, fair enough. I wonder if the new formulation of this code on `LogicT` would indeed work on Windows, using `unix-compat`?

**Comment by dnadales** [comment]
That'd be awesome, since such library would be very useful for us. I'll keep an eye on these packages. Thanks!

**Comment by jwiegley** [comment]
@capitanbatata We don't even need a dependence on `logict`! All that was needed was `MonadPlus`.  See: http://www.haskellforall.com/2014/11/how-to-build-library-agnostic-streaming.html

I'm going to apply this same logic to `pipes-files` to make `hierarchy-files`.
